### ISSUE TITLE
Subscriptable check

### ISSUE THREAD

**Issue by g-pichler** [anikolaienko/py-automapper#13]
Reading through the code I spotted the following line 42 in `automapper/mapper.py`:

`    return hasattr(obj, "__get_item__")`

Is this on purpose, or should it read

`    return hasattr(obj, "__getitem__")`

(`__getitem__` instead of `__get_item__`)?

**Comment by anikolaienko** [comment]
Fixed and published new version: https://pypi.org/project/py-automapper/
Here is the test case for this scenario: https://github.com/anikolaienko/py-automapper/blob/main/tests/test_subscriptable_obj_mapping.py
Appreciate for noticing it!

I also added CI checks now and initial contribution guide:
https://github.com/anikolaienko/py-automapper/blob/main/CONTRIBUTING.md
