### ISSUE TITLE
Can I map across differently named attributes?

### ISSUE THREAD

**Issue by avineshwar** [anikolaienko/py-automapper#3]
- An example could be that I want to map `source_class.myName` to  `destination_class.name`
- This is different from overriding (value in source) or missing (value from source) attribute

**Comment by sonphnt** [comment]
Yes, I am thinking the same about this mapping because source and destination 's fields are not always the same.

**Comment by anikolaienko** [comment]
Sorry for the late reply, currently this is not possible, but I can add this feature shortly.

**Comment by anikolaienko** [comment]
Done. Please check README.md: https://github.com/anikolaienko/py-automapper#different-field-names
